version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: dians2-db
    environment:
      POSTGRES_USER: dians2
      POSTGRES_PASSWORD: sakamDIANS!
      POSTGRES_DB: dians2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dians2-network

  # Spring Boot Application Service
  springboot:
    build: .
    container_name: dians2-springboot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dians2
      SPRING_DATASOURCE_USERNAME: dians2
      SPRING_DATASOURCE_PASSWORD: sakamDIANS!
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    volumes:
      - ./src/main/resources/csv:/app/src/main/resources/csv  # Adjusted mount path
    networks:
      - dians2-network

volumes:
  postgres_data:

networks:
  dians2-network:
    driver: bridge
